# Generated by Django 4.1.4 on 2022-12-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('author', models.TextField(max_length=50)),
                ('price', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('is_published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('cats', 'Котики'), ('dogs', 'Песики'), ('books', 'Книги'), ('plants', 'Растения'), ('furniture&design', 'Мебель и интерьер')], max_length=18, null=True)),
            ],
        ),
    ]
