# Generated by Django 4.1.4 on 2023-01-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
