# Generated by Django 4.1.4 on 2023-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cats', 'Котики'), ('dogs', 'Песики'), ('books', 'Книги'), ('plants', 'Растения'), ('furniture&design', 'Мебель и интерьер')], max_length=50, null=True),
        ),
    ]
