# Generated by Django 4.1.5 on 2023-01-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
